### ISSUE TITLE
本地开发时页面第一次打开会报错

### ISSUE THREAD

**Issue by l246804** [unplugin/unplugin-macros#21]
### Describe the bug

本地开发时每次启动之后第一次打开页面都会报这个错，但是控制台没问题，刷新页面后也正常。在 CodeSandbox 开始创建项目后偶发几次，之后无法复现。

![image](https://github.com/unplugin/unplugin-macros/assets/53589602/3b8c17c9-f2fe-4739-93bc-cc0439a6821b)

### Reproduction

https://codesandbox.io/p/devbox/unplugin-macros-demo-lgy5q8?file=%2Fsrc%2Fassets%2Fdata%2Fpage.ts%3A4%2C8&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqom75k700073o6fmbv7utz8%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqom75k600023o6fm5nvlzb8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqom75k700043o6farg3al33%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqom75k700063o6fjdjs63vv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqom75k600023o6fm5nvlzb8%2522%253A%257B%2522id%2522%253A%2522clqom75k600023o6fm5nvlzb8%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqom75k600013o6fi527cw3t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FHelloWorld.vue%2522%252C%2522id%2522%253A%2522clqomljq500sa3o6fvwnw9nyf%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqomljq500sa3o6fvwnw9nyf%2522%257D%252C%2522clqom75k700063o6fjdjs63vv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqom75k700053o6fq288t3ke%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqom75k700063o6fjdjs63vv%2522%252C%2522activeTabId%2522%253A%2522clqom75k700053o6fq288t3ke%2522%257D%252C%2522clqom75k700043o6farg3al33%2522%253A%257B%2522id%2522%253A%2522clqom75k700043o6farg3al33%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqom75k700033o6fqhidumnb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqom75k700033o6fqhidumnb%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### System Info

```Shell
System:
  OS: Windows 11 10.0.22621
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  Memory: 4.65 GB / 15.66 GB
Binaries:
  Node: 16.20.2 - ~\AppData\Local\pnpm\node.EXE
  npm: 10.2.5 - ~\AppData\Local\pnpm\npm.CMD
  pnpm: 8.6.10 - ~\AppData\Local\pnpm\pnpm.EXE
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Try `unplugin-macros@0.9.2`
