### ISSUE TITLE
希望支持模板字符串

### ISSUE THREAD

**Issue by l246804** [unplugin/unplugin-macros#22]
### Clear and concise description of the problem

目前的宏函数仅支持字面量数据，这让在定义字面量对象时有点儿痛苦，希望能够支持模板字符串，这样内部可以通过 `JSON.stringify()` 等手段将数据转为合适的字符串再进行宏编译处理比较符合预期效果。

### Suggested solution

宏函数支持模板字符串。

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
Could you please provide a demo?

**Comment by l246804** [comment]
我有个需求是在 `vue` 项目中统一定义页面元数据列表，但是为了保证静态数据存在父子引用关系，需要一个编译宏在构建时自动添加 `id` 和 `parentId`。

目前的编译宏代码：

```ts
// utils.ts
export function defineStaticPages(codeOrPages: string | PageMetadata[]) {
  const pages = typeof codeOrPages == "string" ? new Function(`return ${codeOrPages}`)() : codeOrPages;
  let id = 1;
  // ...
  return [...]
}
```

使用方式：
```page.ts
import { defineStaticPages } from './utils' as { type: 'macro' }

// 这里现在只能如此传递
export const staticPages = defineStaticPages(`
  [
    {
      // ...
    }
  ]
`)
```

期望使用方式：
```page.ts
import { defineStaticPages } from './utils' as { type: 'macro' }

// 具备完整的类型提示
const pages: PageMetadata[] = [
  {
    // ...
  }
]

// 这里传递模板字符串
export const staticPages = defineStaticPages(`${ JSON.stringify(pages) }`)
```

**Comment by l246804** [comment]
[插件文档](https://github.com/l246804/vue-app-sdk/wiki/Page#1-%E5%88%9B%E5%BB%BA%E9%9D%99%E6%80%81%E9%A1%B5%E9%9D%A2%E5%85%83%E6%95%B0%E6%8D%AE%E5%88%97%E8%A1%A8)

**Comment by l246804** [comment]
🫣

**Comment by l246804** [comment]
这个功能可以支持吗？

**Comment by sxzz** [comment]
你可以尝试

```ts
import { defineStaticPages } from './utils' as { type: 'macro' }

export const staticPages = defineStaticPages([
  {
    // ... 直接 inline 数据
  }
])
```

**Comment by l246804** [comment]
> 你可以尝试
> 
> ```ts
> import { defineStaticPages } from './utils' as { type: 'macro' }
> 
> export const staticPages = defineStaticPages([
>   {
>     // ... 直接 inline 数据
>   }
> ])
> ```

我也想如此，但是这样会报错误，如果不是设计如此的话那可能是一个 bug？

![df4b7699598356d3bbe87af22eb787f](https://github.com/unplugin/unplugin-macros/assets/53589602/a6fc9519-a841-43aa-a0fd-0b4c9b8dd454)

![04918d8ca2414f7600764b60e860231](https://github.com/unplugin/unplugin-macros/assets/53589602/505b4919-4193-40a1-ab93-a33d45135a78)

**Comment by sxzz** [comment]
Released as `unplugin-macros@0.10.1`
