### ISSUE TITLE
Doesn't work with esbuild

### ISSUE THREAD

**Issue by NotSpaulding** [unplugin/unplugin-macros#25]
### Describe the bug

I get the following error when trying to use this plugin with esbuild:
```
 > src/index.ts:1:47: error: Expected ";" but found "with"
    1 │ import { getRandom, buildTime } from "./macro" with { type: "macro" };
      ╵                                                ~~~~

/workspace/node_modules/esbuild/lib/main.js:1432
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
src/index.ts:1:47: error: Expected ";" but found "with"
    at failureErrorWithLog (/workspace/node_modules/esbuild/lib/main.js:1432:15)
    at /workspace/node_modules/esbuild/lib/main.js:1114:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [
    {
      detail: undefined,
      location: {
        column: 47,
        file: 'src/index.ts',
        length: 4,
        line: 1,
        lineText: 'import { getRandom, buildTime } from "./macro" with { type: "macro" };',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'Expected ";" but found "with"'
    }
  ],
  warnings: []
}

Node.js v20.11.0
 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

https://codesandbox.io/p/devbox/interesting-vaughan-35g6wx?workspaceId=65a17c25-cdc9-4341-87d3-a7fa4055732a

### System Info

```Shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (2) x64 AMD EPYC
    Memory: 2.57 GB / 4.01 GB
    Container: Yes
    Shell: Unknown
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 8.15.1 - /usr/local/share/npm-global/bin/pnpm
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
The esbuild version of your reproduction is too stale. Please try the latest one (at least v0.15)
