### ISSUE TITLE
Expose UnpluginBuildContext through the macro's context

### ISSUE THREAD

**Issue by jraoult** [unplugin/unplugin-macros#28]
### Clear and concise description of the problem

It is a follow up to my exploration started in https://github.com/unplugin/unplugin-macros/issues/27.

I would now need to be able to emit files from the `css` macro to generate the `.css` file, gathering all the rule sets. I know the `transform` handler of an _unplugin_ gets `UnpluginBuildContext` assigned to `this`. It this was passed down to the macro's context alongside the `id` I would then be able to call `this.unpluginBuildContext.emitFile`:

```ts
export function css(
  this: MacroContext & {
    unpluginBuildContext: UnpluginBuildContext;
  },
  code: string,
) {
  const declaration = code;
  const className = hash(declaration);
  const rulesSet = `.${className} { ${declaration} }`;

  this.unpluginBuildContext.emitFile({
    type: "asset",
    name: "style",
    source: rulesSet,
  });

  return className.toString();
}
```

### Suggested solution

I think it starts here: https://github.com/unplugin/unplugin-macros/blob/0430f83244724edf92a727551b0cc7479084ad5b/src/index.ts#L96 where it could be written:

```ts
 transform(code, id) {
      return transformMacros.call(this, code, id, getRunner, deps, options.attrs)
}
```

to pass the context down to `unplugin-macros` and then here https://github.com/unplugin/unplugin-macros/blob/0430f83244724edf92a727551b0cc7479084ad5b/src/core/index.ts#L161-L163 could be:

```ts
const ctx: MacroContext = {
        id,
        unpluginBuildContext: this
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
I've added the `emitFile` method to `MacroContext`, ensuring it's a stable feature that adheres to semantic versioning.

Additionally, I've exposed `unpluginContext` into `MacroContext`. However, please use it cautiously as it may undergo changes or even be removed due to internal implementation adjustments.

**Comment by jraoult** [comment]
@sxzz brillant! Makes sense.
