### ISSUE TITLE
能不能支持 vue template上使用呢

### ISSUE THREAD

**Issue by Colory** [unplugin/unplugin-macros#42]
### Clear and concise description of the problem

能不能支持在 vue template 的xml 部分使用呢
因为vue默认的指令不能完全实现 v-if 的效果

### Suggested solution

想要通过宏的方式 在编译之前将部分template上的代码替换成 `v-if=“xxx('asdasdasdasd')”

例如
```xml
<div $`p`></div>
```
替换成
```
<div v-if="xas('p')"></div>
```

类似这种效果的能不能实现呢

### Validations

- [X] Follow our [Code of Conduct](https://github.com/unplugin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
Macros related to Vue will be considered in Vue Macros. https://github.com/vue-macros/vue-macros
